// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/dialog/index.vue')['default'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TextOver: typeof import('./src/components/text/TextOver.vue')['default'];
  }
}

export {};
